### ISSUE TITLE
DC-DC Buck Step Down Voltage Converter

### ISSUE THREAD

**Issue by GeoBeBee** [Eunanibus/Fritzing-Parts#1]
Hi Eunanibus, In your description you mentioned creating a Fritzing part for the DC-DC Buck Step Down Voltage Converter, but it doesn't seem to be listed. I'm using the same one. Did you find one elsewhere? Thanks ;-)

**Comment by Eunanibus** [comment]
Apologies, no. This was intended but never needed!
